---
title: Trevor Carr
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: page
    permalink: "/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: Trevor Carr is a multidiciplinary designer and front-end developer based in Baltimore, MD.
author: Trevor Carr
permalink: pretty
sass:
  add_charset: true
  sass_dir: assets/sass
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- package.json
- README.md
- CNAME
- node_modules
links:
- url: "/colophon"
  title: colophon
  out: false
- url: "/resume"
  title: résumé
  out: false
- url: mailto:info@trevorcarr.info
  title: 'email: info@trevorcarr.info'
  out: true
- url: https://twitter.com/trevorsee
  title: 'twitter: trevorsee'
  out: true
- url: https://www.instagram.com/_tcarr/
  title: 'instagram: _tcarr'
  out: true
- url: https://github.com/trevorsee
  title: 'github: trevorsee'
  out: true
port: 4001
imgurl: http://res.cloudinary.com/daiyzvpj5/image/fetch
tempurl: http://trevorcarr.info/2017website/
sizes: '100vw'
srcset:
  - 500
  - 750
  - 1000
  - 1250
  - 1500
  - 1750
  - 2000
  - 2250
  - 2500
  - 2750
  - 3000
gems:
- jekyll/imgix
imgix:
  source: default-value.imgix.net
