---
title: 2017 Portfolio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: page
    permalink: "/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
author: Trevor Carr
permalink: pretty
sass:
  add_charset: true
  sass_dir: assets/sass
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- package.json
- README.md
- CNAME
- node_modules
links:
- url: "/booksandreading"
  title: books & reading
  out: false
- url: "/resume"
  title: résumé
  out: false
- url: mailto:info@trevorcarr.info
  title: 'email: info@trevorcarr.info'
  out: true
- url: https://twitter.com/trevorsee
  title: 'twitter: trevorsee'
  out: true
- url: https://www.instagram.com/_tcarr/
  title: 'instagram: _tcarr'
  out: true
port: 4001
imgurl: "http://res.cloudinary.com/daiyzvpj5/image/upload"
